### ISSUE TITLE
Docs: Add information about https requirement

### ISSUE THREAD

**Issue by mandrasch** [s2b/ddev-vite-sidecar#7]
I don't know if this can be checked automatically, but some DDEV users tend to forget [setting up mkcert properly](https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#ddev-installation-macos).

This results in a fallback to `http://` when running DDEV projects, which results in the error `Access to script at ... has been blocked / CORS`.

See e.g.

- https://discord.com/channels/664580571770388500/1247970933461749780
- https://typo3.slack.com/archives/C05JYUT3CDP/p1724677414250889

So running DDEV projects with `https://` is a requirement for this to work - would be maybe helpful to mention this in the docs / troubleshooting.

**Comment by s2b** [comment]
Hm, I'd rather allow usage without https. How is CORS related to HTTPS? 🤔

**Comment by mandrasch** [comment]
Guess the real problem is that https://vite. is not reachable there - and you try to connect to it? (But just a guess, because the T3 poster had also Bad Gateway)

There is also a warning when doing `ddev start` that mkcert is not properly setup - don't know if I would encourage non-https-usage, since other problems might arise (and it's not a proper DDEV install). But you could discuss this with stas or randy :) ([Source](https://discord.com/channels/664580571770388500/1247970933461749780/1247977984971772025))

**Comment by mandrasch** [comment]
Okay, the [TYPO3 thread](https://typo3.slack.com/archives/C05JYUT3CDP/p1724677414250889) might be another issue.

Just wanted to let know that a lot of support requests in DDEV Discord regarding Vite were missing mkcert execution / non-http (and people ignored the DDEV warning on `ddev start`). We also thought about adding a warning to the [Vite article](https://ddev.com/blog/working-with-vite-in-ddev/) since so many people ran into this. 🤷

**Comment by rfay** [comment]
DDEV pesters people on every `ddev start` if they haven't done `mkcert -install`. They can ignore it. But this one-time action provides easy trusted HTTPS forever on the machine.

**Comment by s2b** [comment]
Thank you for your input! I'll look into the specific TYPO3 issue tomorrow in a screensharing session and see if it is a problem I can address.

Concerning the add-on, I think the main issue is that I set the environment variable to `https://vite.myproject.ddev.site`. So if you don't want to use https (why would you do that!?), you cannot use the environment variable. I don't think that this is something I should change/improve.

**Comment by mandrasch** [comment]
yeah, that's why I proposed a simple disclaimer / information in the docs that https is required 👍 
(additionally maybe a check in the start command of your plugin if https is really used, but don't know if this is easily possible)

**Comment by s2b** [comment]
I just checked it in a test setup: `https` is not required to use the add-on. Only if you want to use the pre-set environment variable, `https` is used as a fixed value. However, this is already mentioned in the readme file.

Concerning the CORS issue, there was a bug in the nginx configuration, see #9
